# -*- coding: utf-8 -*-
"""Actividad 4 - Manejo del lenguaje de programación Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115yx3KHnXMto7qqfmlmcVNcLD0aCwFsL

### 1. Media
La fórmula de la media aritmética es:

$$
\text{Media} = \frac{1}{n} \sum_{i=1}^n x_i
$$
donde:
- \( x_i \): valores del conjunto de datos
- \( n \): número total de valores

### 2. Mediana
La fórmula de la mediana depende de si el número de elementos es impar o par:

- Si \( n \) es impar:
$$
\text{Mediana} = x_{\frac{n+1}{2}}
$$

- Si \( n \) es par:
$$
\text{Mediana} = \frac{x_{\frac{n}{2}} + x_{\frac{n}{2} + 1}}{2}
$$

### 3. Moda
La moda es el valor que más veces se repite en el conjunto de datos. Si hay más de un valor con la máxima frecuencia, el conjunto es multimodal.

### 4. Varianza
La fórmula de la varianza es:

$$
\text{Varianza} = \frac{1}{n} \sum_{i=1}^n (x_i - \text{Media})^2
$$

donde:
- \( x_i \): valores del conjunto de datos
- \( \text{Media} \): la media del conjunto de datos

### 5. Desviación Estándar
La desviación estándar es la raíz cuadrada de la varianza:

$$
\text{Desviación Estandar} = \sqrt{\text{Varianza}}
$$

### 6. Coeficiente de Variación
El coeficiente de variación es:

$$
\text{Coeficiente de Variación} = \frac{\text{Desviación Estandar}}{\text{Media}} \times 100
$$

### 7. Normalización Z
La fórmula para normalización Z es:

$$
Z = \frac{x_i - \text{Media}}{\text{Desviación Estandar}}
$$

donde:
- \( Z \): valor estandarizado
- \( x_i \): valor del conjunto de datos

Media
Descripción: La media aritmética es el promedio de un conjunto de datos. Se calcula sumando todos los valores y dividiéndolos por la cantidad total de valores.
"""

def calcular_media(datos):
    suma = sum(datos)
    n = len(datos)
    return suma / n

# Ejemplo
datos = [10, 15, 20, 25, 30]
print("Media:", calcular_media(datos))

"""Mediana
Descripción: La mediana es el valor que se encuentra en el centro del conjunto de datos ordenado. Si el número de elementos es par, la mediana es el promedio de los dos valores centrales.
"""

def calcular_mediana(datos):
    datos_ordenados = sorted(datos)
    n = len(datos)
    mitad = n // 2
    if n % 2 == 0:
        return (datos_ordenados[mitad - 1] + datos_ordenados[mitad]) / 2
    else:
        return datos_ordenados[mitad]

# Ejemplo
datos = [10, 15, 20, 25, 30]
print("Mediana:", calcular_mediana(datos))

"""Moda
Descripción: La moda es el valor que más veces se repite en un conjunto de datos. Puede haber más de una moda si varios valores tienen la misma frecuencia máxima.
"""

def calcular_moda(datos):
    frecuencia = {}
    for valor in datos:
        if valor in frecuencia:
            frecuencia[valor] += 1
        else:
            frecuencia[valor] = 1
    moda = [key for key, value in frecuencia.items() if value == max(frecuencia.values())]
    return moda

# Ejemplo
datos = [10, 15, 20, 20, 30, 30, 30]
print("Moda:", calcular_moda(datos))

"""Varianza
Descripción: La varianza mide la dispersión de los datos con respecto a la media. Es el promedio de los cuadrados de las diferencias entre cada valor y la media.
"""

def calcular_varianza(datos):
    media = calcular_media(datos)
    suma_cuadrados = sum((x - media) ** 2 for x in datos)
    return suma_cuadrados / len(datos)

# Ejemplo
datos = [10, 15, 20, 25, 30]
print("Varianza:", calcular_varianza(datos))

"""Desviación Estándar
Descripción: La desviación estándar es la raíz cuadrada de la varianza y mide la dispersión de los datos en las mismas unidades que el conjunto original.
"""

import math

def calcular_desviacion_estandar(datos):
    varianza = calcular_varianza(datos)
    return math.sqrt(varianza)

# Ejemplo
datos = [10, 15, 20, 25, 30]
print("Desviación Estándar:", calcular_desviacion_estandar(datos))

"""Coeficiente de Variación
Descripción: El coeficiente de variación es una medida de la dispersión relativa y se calcula dividiendo la desviación estándar entre la media, expresado como porcentaje.
"""

def calcular_coeficiente_variacion(datos):
    media = calcular_media(datos)
    desviacion_estandar = calcular_desviacion_estandar(datos)
    return (desviacion_estandar / media) * 100

# Ejemplo
datos = [10, 15, 20, 25, 30]
print("Coeficiente de Variación:", calcular_coeficiente_variacion(datos), "%")

"""Normalización Z
Descripción: La normalización Z transforma los datos para que tengan media 0 y desviación estándar 1. Para cada valor, se resta la media y se divide entre la desviación estándar.
"""

def normalizar_z(datos):
    media = calcular_media(datos)
    desviacion_estandar = calcular_desviacion_estandar(datos)
    return [(x - media) / desviacion_estandar for x in datos]

# Ejemplo
datos = [10, 15, 20, 25, 30]
print("Normalización Z:", normalizar_z(datos))